Log:
  Level: 4 # 0 - panic, 1 - fatal, 2 - error, 3 - warn, 4 - info, 5 - debug, 6 - trace

Bot:
  Goroutine: false # Обрабатывать ли события асинхронно

Vk:
  Token: 'vk1.a.KeGjwzxcV3ESylkzq3EuB8WAE_xuQUR2ZDTIMyHWZqjQgebgwCqCj0k25K6U9kZFg65xxiPfeHgJN9OFVz9eK_ljD8SaJRIU4XNkJeKWFka4Eq8SVpYda2oajMTqbwFD7ytpYj28tPQKT3imuB4UB_AcTQWhTD23F-VvjlW_pQpNsu9YtvfgqGjldghW29CKtUtmW2YqRjMP93Ppaqv6EA'
  GroupId: 220348328
  Command:
    Prefix:
      - '/'
      - '.'
      - '!'
